# JSAI SIG 用テンプレ (jarticle + jsaisig.sty). pLaTeX2e + UTF-8 で dvipdfmx 経由
# スタイルファイルは再配布不可のため git 管理外. 配布 zip を ../jsai_sig-1_0_0/ に展開して参照
$latex = 'platex -kanji=utf8 -synctex=1 -halt-on-error -file-line-error %O %S';
$bibtex = 'pbibtex %O %B';
$dvipdf = 'dvipdfmx %O -o %D %S';
$pdf_mode = 3;
$ENV{'TEXINPUTS'} = '../jsai_sig-1_0_0//:' . ($ENV{'TEXINPUTS'} // '');
$ENV{'BSTINPUTS'} = '../jsai_sig-1_0_0//:' . ($ENV{'BSTINPUTS'} // '');
