# jsaiart.cls は pLaTeX2e 専用のため dvi 経由でビルドする
# JSAI スタイルファイルは再配布不可のため git 管理外. 配布 zip を ../jsai_5_0_1_template/ に展開して参照する
$latex = 'platex -synctex=1 -halt-on-error -file-line-error %O %S';
$bibtex = 'pbibtex %O %B';
$dvipdf = 'dvipdfmx %O -o %D %S';
$pdf_mode = 3;
$ENV{'TEXINPUTS'} = '../jsai_5_0_1_template/sty//:' . ($ENV{'TEXINPUTS'} // '');
$ENV{'BSTINPUTS'} = '../jsai_5_0_1_template/sty//:' . ($ENV{'BSTINPUTS'} // '');
